Repository Builditluc/wiki-tui, pull requests merged in 2023-02, with the labels that each got.

#147 Create Api Handler
  Cargo.lock
  Cargo.toml
  src/wiki/api/mediawiki.rs
  src/wiki/api/mod.rs
  src/wiki/mod.rs
Labels: state: approved, type: refactor

#149 Create new parser system
  src/main.rs
  src/wiki/api/mediawiki.rs
  src/wiki/article_new.rs
  src/wiki/mod.rs
  src/wiki/parser/elements.rs
  src/wiki/parser/mediawiki.rs
  src/wiki/parser/mod.rs
  src/wiki/parser/traits.rs
  src/wiki/section.rs
Labels: state: approved, type: refactor

#150 Rework backend
  Cargo.lock
  Cargo.toml
  README.md
  src/main.rs
  src/ui/article/content.rs
  src/ui/article/lines.rs
  src/ui/article/links.rs
  src/ui/article/mod.rs
  src/ui/article/view.rs
  src/ui/search/display.rs
  src/ui/search/mod.rs
  src/ui/toc.rs
  src/wiki/article.rs
  src/wiki/article/builder.rs
  src/wiki/article/compiled_article.rs
  src/wiki/article/element.rs
  src/wiki/article/mod.rs
  src/wiki/article/parser.rs
  src/wiki/article/toc.rs
  src/wiki/mod.rs
  src/wiki/parser.rs
  src/wiki/search.rs
  src/wiki/search/builder.rs
  src/wiki/search/compiled_search.rs
  src/wiki/search/info.rs
  src/wiki/search/metadata.rs
  src/wiki/search/mod.rs
  src/wiki/search/properties.rs
  src/wiki/search/result.rs
  src/wiki/search/sort_order.rs
Labels: type: refactor, bug-type: parser, bug-type: ui

#151 Fix large gaps before and after lists
  src/wiki/article.rs
  src/wiki/parser.rs
  src/wiki/search.rs
Labels: state: approved, type: bug, bug-type: parser

#152 Fix html tags in toc
  src/wiki/article.rs
Labels: state: approved, type: bug, bug-type: ui

#153 Fix missing whitespace on list items starting with a special character
  src/ui/article/lines.rs
  src/wiki/article.rs
  src/wiki/parser.rs
Labels: state: approved, type: bug, bug-type: parser

#154 Fix incorrect error message formatting when opening links
  src/ui/article/mod.rs
Labels: state: approved, type: bug, bug-type: ui

#155 Fix wrong error origin in dialogs
  src/ui/utils.rs
Labels: state: approved, type: bug, bug-type: ui

#156 Add changelog and use auto for creating releases
  .autorc
  .github/workflows/cd.yml
  .gitignore
  CHANGELOG.md
  docs/contributing/maintainers.md
Labels: state: approved, type: chore, type: documentation

#158 Fix no redirect messages being shown
  src/wiki/parser.rs
Labels: state: approved, type: bug, bug-type: parser

#159 Fix whitespace at the top of some articles
  src/wiki/parser.rs
Labels: state: approved, type: bug, bug-type: parser

#160 Fix disambiguations not shown
  src/wiki/parser.rs
Labels: state: approved, type: bug, bug-type: parser

#162 Exit when no layers are present anymore
  src/main.rs
Labels: state: approved, type: feature
