Repository Builditluc/wiki-tui, pull requests merged in 2023-05, with the labels that each got.

#173 Display header numbers in the article
  src/wiki/article.rs
  src/wiki/parser.rs
Labels: state: approved, type: feature

#174 Update documentation
  LICENSE
  LICENSE.txt
  docs/.overrides/main.html
  docs/assets/images/border-heavy-1.png
  docs/assets/images/border-heavy-2.png
  docs/assets/images/border-round-1.png
  docs/assets/images/border-round-2.png
  docs/assets/images/border-thin-1.png
  docs/assets/images/border-thin-2.png
  docs/assets/images/preview-1.png
  docs/assets/images/preview-2.png
  docs/assets/images/preview-3.png
  docs/changelog/upgrade.md
Labels: state: approved, type: documentation

#175 Change log directory
  docs/changelog/upgrade.md
  docs/configuration/index.md
  docs/configuration/logging.md
  docs/getting-started/crash.md
  src/cli.rs
  src/config.rs
  src/error.rs
  src/logging.rs
  src/main.rs
  src/wiki/parser.rs
Labels: state: approved, breaking-change

#181 Fix url encoded links
  Cargo.lock
  Cargo.toml
  src/logging.rs
  src/ui/article/view.rs
  src/wiki/parser.rs
Labels: state: approved, type: bug, bug-type: parser

#180 Vim movements (ctrl+d, ctrl+u, gg, G)
  docs/configuration/keybindings.md
  src/cli.rs
  src/ui/scroll.rs
Labels: state: approved, type: feature
