Repository Builditluc/wiki-tui, pull requests merged in 2023-04, with the labels that each got.

#170 Fix typo
  docs/configuration/api.md
Labels: type: documentation, ignore-release

#171 Improve speed of ci workflow
  .github/workflows/ci.yml
  rust-toolchain
Labels: type: chore, ignore-release

#168 Add Language Selection
  Cargo.lock
  Cargo.toml
  data/languages.json
  docs/changelog/upgrade.md
  docs/configuration/api.md
  docs/configuration/keybindings.md
  docs/getting-started/usage.md
  src/cli.rs
  src/config.rs
  src/lib.rs
  src/main.rs
  src/ui/article/mod.rs
  src/ui/language_selector.rs
  src/ui/mod.rs
  src/ui/search/display.rs
  src/ui/search/mod.rs
  src/wiki/article.rs
  src/wiki/language.rs
  src/wiki/mod.rs
  src/wiki/search.rs
Labels: state: approved, type: documentation, type: feature

#172 Fix cargo publish
  Cargo.toml
Labels: type: bug, ignore-release
